### ISSUE TITLE
Segmentation fault on OSX anaconda python 

### ISSUE THREAD

**Issue by RasmusFonseca** [Eigenstate/vmd-python#13]
Just did a clean install of anaconda and I'm now getting segfaults when importing:
```
MBPro:~/Programs $ conda activate py27
(py27) MBPro:~/Programs $ python
Python 2.7.14 |Anaconda, Inc.| (default, Dec  7 2017, 11:07:58)
[GCC 4.2.1 Compatible Clang 4.0.1 (tags/RELEASE_401/final)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import vmd
Segmentation fault: 11
(py27) MBPro:~/Programs $ conda activate base
(base) MBPro:~/Programs $ python
Python 3.6.4 |Anaconda, Inc.| (default, Jan 16 2018, 12:04:33)
[GCC 4.2.1 Compatible Clang 4.0.1 (tags/RELEASE_401/final)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import vmd
Segmentation fault: 11
```

**Comment by Eigenstate** [comment]
Okay I have added a flag to the build process that will build the main library (not the plugins though) with debug symbols.

``
git pull
python setup.py build --debug
python setup.py install
``

Load that up into the debugger and you'll get a more helpful stack trace.
All of the source files live in vmd/vmd_src/src.

**Comment by RasmusFonseca** [comment]
Ok, so for the record, creating a conda-environment the following way:
```
conda create -n vmd-python python=3.6 netcdf4 numpy expat tk=8.5
conda activate vmd-python
cd path/to/vmd-python
python setup.py build
python setup.py install
```
.. works. I guess the problem was that it was detecting the specific tcl version (8.5) in `/usr/lib` but not caring where it got the includes from, so they didn't match because the most recent conda version was 8.6. Specifically installing tk 8.5 in conda solved this.
