### ISSUE TITLE
ImportError: libtcl8.5.so: cannot open shared object file: No such file or directory

### ISSUE THREAD

**Issue by OleinikovasV** [Eigenstate/vmd-python#15]
Hi!
After downloading and successfully installing the latest GitHub version to my Linux machine, I get the following error while importing the new module:

```
ImportError                               Traceback (most recent call last)
<ipython-input-1-1ec58bc80a6c> in <module>()
----> 1 import vmd

/home/vladas/software/anaconda/lib/python2.7/site-packages/vmd/__init__.py in <module>()
     21 
     22 # Load the library
---> 23 vmd = imp.load_dynamic(__name__, resource_filename(__name__, "libvmd.so"))
     24 
     25 # These modules define classes for convenient manipulation of VMD state.

ImportError: libtcl8.5.so: cannot open shared object file: No such file or directory
```

**Comment by jvermaas** [comment]
Semi-obvious question: is there a libtcl8.5 in your path? libvmd.so is a shared library, so it needs to be able to find other shared libraries. I can't quite tell if this is a linux machine or not, but on Ubuntu and other debian derivatives, all you'd need to do is "sudo apt-get install libtcl8.5", and your system will be able to find the library.

**Comment by OleinikovasV** [comment]
Indeed this was something external, related to conda path issues. What helped was locating the right path to file and making sure the corresponding python was used:
`sudo find / -iname "*libtcl8.5.so"`
