### ISSUE TITLE
render produce wrong output file when running through script

### ISSUE THREAD

**Issue by huangziyan11111** [Eigenstate/vmd-python#31]
I wrote a code: visual.py, just two step:load and render. I can correctly run when I firstly get into python environment, and run step by step. While I run through script (python visual.py), the output file 1fqy.dat can not produce correctly. I don't know why output get wrong as I run the same code as before.

the content of script visual.py:
from vmd import Molecule
from Molecule import *
from vmd import render
molecule.load('pdb','1fqy.pdb')
render.render(method="Tachyon",filename="1fqy.dat")

**Comment by Eigenstate** [comment]
I need some more information to be able to help you with your problem. A couple questions:

- What's the output you're getting? Are there any error messages or exceptions? Is 1fqy.dat created?
- Is tachyon installed on your machine?
- Is your code exactly as written? There is both a `molecule` module and a `Molecule` class, and it is case sensitive. So you'd want `from vmd import molecule` with the lowercase m.

**Comment by huangziyan11111** [comment]
Thank you for you reply, I get the right result through adding one line: "**display.update()**" before "render.render(method="Tachyon",filename="1fqy.dat")". output file 1fqy.dat is the same as I run with firstly getting into python environment. I check what you suggest, everything is fine. ^_^
