### ISSUE TITLE
Does this package can invoke a VMD GUI or just uses the python-api of VMD

### ISSUE THREAD

**Issue by Roy-Kid** [Eigenstate/vmd-python#38]
I want to use VMD to visualize my own python package. Does this package can visualize my data or just use VMD python-api to compute some data?

**Comment by Eigenstate** [comment]
This package doesn't include the VMD GUI in terms of the traditional interface. You'll still just see your Python terminal. However, it is capable of doing off-screen rendering (the `render` module) to generate figures. You can compile VMD with Python support if you're interested in having full GUI functionality.
