### ISSUE TITLE
Wrong path to netcdf build flags

### ISSUE THREAD

**Issue by giacomofiorin** [Eigenstate/vmd-python#4]
On Ubuntu 16.04 (netcdf 4.4) pip (version 9.0.1) gives the following error: 
```
error: [Errno 2] No such file or directory: '/usr/lib/libnetcdf.settings'
```
The Debian package for libnetcdf-dev has the file only in the build-specific library path.

The conda installer seems to work OK.

**Comment by Eigenstate** [comment]
Fixed in 86e4d43, I hope. I made the whole build process much more intelligent with regard to finding libraries.

The pip package is updated, so try it again. I haven't updated the conda builds because I have some parm7 parser patches planned for tomorrow.
