### ISSUE TITLE
__init__.py not found

### ISSUE THREAD

**Issue by sjzhao** [Eigenstate/vmd-python#40]
Hi Robin, I used python3 setup.py build to build and got that the init script not found. Regarding the compiling, I think all the linked .so file created but I don't know the last few lines matters?
Here it is:
VMD installation complete.  Enjoy!
/bin/sh: line 0: cd: ../doc: No such file or directory
running build_py
package init file 'vmd/__init__.py' not found (or not a regular file)

**Comment by Eigenstate** [comment]
Those two messages can be ignored. The message about `__init__.py` can be ignored since the created .so file contains init instructions for the module.

**Comment by sjzhao** [comment]
Thank you Robin.
