### ISSUE TITLE
Can't use topotools::mergetools when evaluating a tcl script.

### ISSUE THREAD

**Issue by GregorySchwing** [Eigenstate/vmd-python#45]
A tcl script which runs find using vmd version "VMD for LINUXAMD64, version 1.9.3 (November 30, 2016)"

like this 
$ vmd < scripts/merge_protein_and_solvent_box.tcl

Or starting the tkconsole and sourcing the script, also works fine.

Fails when using it like this 

from vmd import evaltcl
ions = evaltcl("source scripts/merge_protein_and_solvent_box.tcl

[problem.zip](https://github.com/Eigenstate/vmd-python/files/11057219/problem.zip)

**Comment by GregorySchwing** [comment]
Traceback (most recent call last):
  File "scripts/amber_2_charmm.py", line 28, in <module>
    ions = evaltcl("source scripts/merge_protein_and_solvent_box.tcl")
ValueError: invalid command name "TopoTools::mergemols"

**Comment by jvermaas** [comment]
Where are you doing a `package require topotools` or similar in there? That is what gives you `TopoTools::mergemols`. "Normal" VMD will load some set of packages automatically, but vmd-python does not do that by default.

**Comment by GregorySchwing** [comment]
That worked.  Thanks
