### ISSUE TITLE
libtcl8.5.so ImportError

### ISSUE THREAD

**Issue by osercinoglu** [Eigenstate/vmd-python#7]
Hi!

I've installed vmd-python using conda install (python 3.6) procedure.
It seemed to install fine with no errors, but when I try to import the module in IPython using

`import vmd`

I get the following error:
`ImportError: libtcl8.5.so: cannot open shared object file: No such file or directory`

I searched for libtcl8.5.so in my conda installation lib folder. It seems I had libtcl8.6.so, not libtcl8.5.so, so I simply made a copy of libtcl8.6.so and renamed it to libtcl.8.5.so. Then I was able to import with no problems, but I guess this is not an expected behaviour. Why do you think libtcl8.6.so is not detected?

**Comment by jvermaas** [comment]
Because at compilation time you need to pick one or the other, and 8.5 is still the default.

**Comment by Eigenstate** [comment]
Oops, I built the binaries against libtcl8.5 and some versions of python now ship with libtcl8.6. I've added tk=8.5.* as a dependency so conda will grab the correct library when installing the binaries.

You can either `conda install tk=8.5*` or reinstall vmd-python (new version is 2.0.2). I don't have an OSX binary for this one yet though. Although symlinking the newer library version worked for you, it is not often the case that different library versions will be completely compatible.
