### ISSUE TITLE
netcdf error when running python setup.py build 

### ISSUE THREAD

**Issue by akma327** [Eigenstate/vmd-python#9]
[akm64@farnam2 vmd-python]$ python setup.py build
running build
running build_py
Compiling VMD
Finding libraries...
   LIB: libtcl8.5.so -> /usr/lib64
   INC: tcl.h -> /usr/include
   LIB: libsqlite3.so -> /usr/lib64
   INC: sqlite3.h -> /usr/include
   LIB: libexpat.so -> /usr/lib64
   INC: expat.h -> /usr/include
WARNING: Could not find library file 'libnetcdf.so' in standard library directories.
 Defaulting to: '/usr/lib/libnetcdf.so'
   LIB: libnetcdf.so -> /usr/lib

WARNING: Could not find include file 'netcdf.h' in standard include directories.
 Defaulting to: '/usr/include/netcdf.h'
   INC: netcdf.h -> /usr/include/netcdf.h
   LIB: libpython2.7*.so -> /usr/lib64
Setting environment variables
Deleting previous plugin directory /ysm-gpfs/home/akm64/lib/vmd-python/build/lib/vmd/plugins
Compiling plugins to /ysm-gpfs/home/akm64/lib/vmd-python/build/lib/vmd/plugins
Building Molecule File Reader plugins
src/netcdfplugin.c:22:20: fatal error: netcdf.h: No such file or directory
 #include <netcdf.h>
                    ^
compilation terminated.
make[2]: *** [../compile/lib_LINUXAMD64/molfile/netcdfplugin.o] Error 1
make[1]: *** [molfilelibs] Error 1
make: *** [LINUXAMD64] Error 2
Traceback (most recent call last):
  File "setup.py", line 293, in <module>
    'test': VMDTest,
  File "/usr/lib64/python2.7/distutils/core.py", line 152, in setup
    dist.run_commands()
  File "/usr/lib64/python2.7/distutils/dist.py", line 953, in run_commands
    self.run_command(cmd)
  File "/usr/lib64/python2.7/distutils/dist.py", line 972, in run_command
    cmd_obj.run()
  File "setup.py", line 32, in run
    self.execute(self.compile, [], msg="Compiling VMD")
  File "/usr/lib64/python2.7/distutils/cmd.py", line 349, in execute
    util.execute(func, args, msg, dry_run=self.dry_run)
  File "/usr/lib64/python2.7/distutils/util.py", line 324, in execute
    func(*args)
  File "setup.py", line 52, in compile
    check_call(cmd, cwd=srcdir)
  File "/usr/lib64/python2.7/subprocess.py", line 542, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['/ysm-gpfs/home/akm64/lib/vmd-python/vmd/install.sh', 'LINUXAMD64', '/ysm-gpfs/home/akm64/lib/vmd-python/build/lib/vmd', '/usr/']' returned non-zero exit status 2

**Comment by RasmusFonseca** [comment]
Have you tried `brew install netcdf`?

**Comment by akma327** [comment]
awesome that works!

**Comment by RasmusFonseca** [comment]
Great, @Eigenstate I'd suggest that the README section on dependencies came before installation instructions and explicitly stated that the easiest way to satisfy those dependencies on mac is to install [homebrew](https://brew.sh/) and run `brew install netcdf; pip install numpy`.

**Comment by akma327** [comment]
On a related note, I'm trying to replicate the brew install on a computing cluster am now facing issues on getting brew downloaded on linux. Any ideas on if it is a permission issue to get around?

sh -c "$(curl -fsSL https://raw.githubusercontent.com/Linuxbrew/install/master/install.sh)"

HEAD is now at c85a991 Python.user_site_packages: Check python suceeds [Linux] (#563)
==> Downloading https://homebrew.bintray.com/bottles-portable/portable-ruby-2.3.3.x86_64_linux.bottle.1.tar.gz
######################################################################## 100.0%
==> Pouring portable-ruby-2.3.3.x86_64_linux.bottle.1.tar.gz
==> Tapping homebrew/core
Cloning into '/ysm-gpfs/home/akm64/.linuxbrew/Homebrew/Library/Taps/homebrew/homebrew-core'...
remote: Counting objects: 4748, done.
remote: Compressing objects: 100% (4521/4521), done.
remote: Total 4748 (delta 38), reused 370 (delta 9), pack-reused 0
Receiving objects: 100% (4748/4748), 4.01 MiB | 0 bytes/s, done.
Resolving deltas: 100% (38/38), done.
Tapped 4509 formulae (4,793 files, 12.6MB)
Already up-to-date.
==> Installation successful!

==> Homebrew has enabled anonymous aggregate user behaviour analytics.
Read the analytics documentation (and how to opt-out) here:
  http://docs.brew.sh/Analytics.html

==> Next steps:
- Install the Linuxbrew dependencies if you have sudo access:
  Debian, Ubuntu, etc.
    sudo apt-get install build-essential
  Fedora, Red Hat, CentOS, etc.
    sudo yum groupinstall 'Development Tools'
  See http://linuxbrew.sh/#dependencies for more information.
- Add Linuxbrew to your ~/.profile by running
    echo 'export PATH="/ysm-gpfs/home/akm64/.linuxbrew/bin:$PATH"' >>~/.profile
    echo 'export MANPATH="/ysm-gpfs/home/akm64/.linuxbrew/share/man:$MANPATH"' >>~/.profile
    echo 'export INFOPATH="/ysm-gpfs/home/akm64/.linuxbrew/share/info:$INFOPATH"' >>~/.profile
- Add Linuxbrew to your PATH
    PATH="/ysm-gpfs/home/akm64/.linuxbrew/bin:$PATH"
- We recommend that you install GCC by running:
    brew install gcc
- Run `brew help` to get started
- Further documentation: 
    http://docs.brew.sh
Warning: /ysm-gpfs/home/akm64/.linuxbrew/bin is not in your PATH.
[akm64@farnam2 MDContactNetworks]$ brew help
bash: brew: command not found...

**Comment by RasmusFonseca** [comment]
Ah, brew is a mac-only package manager. On linux you'd want whatever package manager the distro uses. For ubuntu I think it's Synaptic (i.e. `apt-get install ...`)

**Comment by Eigenstate** [comment]
On linux you can just install the binary, no need to build!
```conda install -c rbetz vmd-python```

**Comment by akma327** [comment]
Hmm, I'm on a new cluster right now and get 
[akm64@farnam2 vmd-python]$ conda install -c https://conda.anaconda.org/rbetz vmd-python
bash: conda: command not found...
[akm64@farnam2 vmd-python]$ conda --version
bash: conda: command not found...

How should I install conda?

**Comment by RasmusFonseca** [comment]
https://www.anaconda.com/download

**Comment by akma327** [comment]
Awesome! 2 for 2! works on local machine and a foreign cluster :D
